"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var QuestionTypes;
(function (QuestionTypes) {
    QuestionTypes["Calculated"] = "calculated";
    QuestionTypes["CalculatedMulti"] = "calculatedmulti";
    QuestionTypes["CalculatedSimple"] = "calculatedsimple";
    QuestionTypes["DdImageOrText"] = "ddimageortext";
    QuestionTypes["DdMarker"] = "ddmarker";
    QuestionTypes["DdWTos"] = "ddwtos";
    QuestionTypes["Description"] = "description";
    QuestionTypes["Essay"] = "essay";
    QuestionTypes["GapSelect"] = "gapselect";
    QuestionTypes["Match"] = "match";
    QuestionTypes["MissingType"] = "missingtype";
    QuestionTypes["MultiAnswer"] = "multianswer";
    QuestionTypes["MultiChoice"] = "multichoice";
    QuestionTypes["Numerical"] = "numerical";
    QuestionTypes["Random"] = "random";
    QuestionTypes["RandomSAMatch"] = "randomsamatch";
    QuestionTypes["ShortAnswer"] = "shortanswer";
    QuestionTypes["Tests"] = "tests";
    QuestionTypes["TrueFalse"] = "truefalse";
})(QuestionTypes || (QuestionTypes = {}));
exports.default = QuestionTypes;
